image: alpine/latest
packages:
  - uv
  - gcc
  - python3-dev
  - postgresql-dev

secrets:
  - b88a4c2c-944c-42a6-9fbb-7483049c458a

sources:
  - git@git.sr.ht:~sfermigier/kenobix

tasks:
  - install: |
      cd kenobix
      uv sync --all-packages --all-extras --all-groups
  - test: |
      cd kenobix
      uv run pytest -q --tb=short
  - lint: |
      cd kenobix
      uv run make lint
  - nox: |
      cd kenobix
      uvx nox

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
